Repository open-mmlab/mmyolo, pull requests merged in 2022-11, with the labels that each got.

#199 [Feature] Support YOLOv5 YOLOv6 YOLOX Deploy in mmdeploy
  configs/deploy/detection_tensorrt-fp16_dynamic-192x192-960x960.py
  configs/deploy/detection_tensorrt-fp16_static-640x640.py
  configs/deploy/detection_tensorrt-int8_dynamic-192x192-960x960.py
  configs/deploy/detection_tensorrt-int8_static-640x640.py
  configs/deploy/detection_tensorrt_dynamic-192x192-960x960.py
  configs/deploy/detection_tensorrt_static-640x640.py
  mmyolo/deploy/models/dense_heads/yolov5_head.py
  mmyolo/deploy/models/layers/__init__.py
  mmyolo/deploy/models/layers/bbox_nms.py
Labels: deployment, Feature:P0

#220 [DOC] Add deploy guide doc
  docs/zh_cn/advanced_guides/basic_deployment_guide.md
  docs/zh_cn/advanced_guides/yolov5_deploy.md
Labels: deployment, documentation

#214 [Feature] Add static shape model config
  configs/deploy/model/yolov5_s-static.py
  configs/deploy/model/yolov6_s-static.py
Labels: deployment

#183 [Feature] Support YOLOv6 training
  configs/yolov6/README.md
  configs/yolov6/yolov6_n_syncbn_fast_8xb32-300e_coco.py
  configs/yolov6/yolov6_n_syncbn_fast_8xb32-400e_coco.py
  configs/yolov6/yolov6_s_syncbn_8xb32-400e_coco.py
  configs/yolov6/yolov6_s_syncbn_fast_8xb32-300e_coco.py
  configs/yolov6/yolov6_s_syncbn_fast_8xb32-400e_coco.py
  configs/yolov6/yolov6_t_syncbn_fast_8xb32-300e_coco.py
  configs/yolov6/yolov6_t_syncbn_fast_8xb32-400e_coco.py
  demo/image_demo.py
  mmyolo/engine/hooks/__init__.py
  mmyolo/engine/hooks/switch_to_deploy_hook.py
  mmyolo/models/dense_heads/yolov6_head.py
  mmyolo/models/layers/yolo_bricks.py
  mmyolo/models/losses/iou_loss.py
  mmyolo/models/task_modules/__init__.py
  mmyolo/models/task_modules/assigners/__init__.py
  mmyolo/models/task_modules/assigners/batch_atss_assigner.py
  mmyolo/models/task_modules/assigners/batch_task_aligned_assigner.py
  mmyolo/models/task_modules/assigners/utils.py
  mmyolo/utils/__init__.py
  mmyolo/utils/misc.py
  tests/test_engine/test_hooks/test_switch_to_deploy_hook.py
  tests/test_models/test_detectors/test_yolo_detector.py
  tests/test_models/test_task_modules/__init__.py
  tests/test_models/test_task_modules/test_assigners/__init__.py
  tests/test_models/test_task_modules/test_assigners/test_batch_atss_assigner.py
  tests/test_models/test_task_modules/test_assigners/test_batch_task_aligned_assigner.py
  tools/test.py
Labels: Feature:P0

#198 [Docs] yolov5_description.md in English
  docs/en/algorithm_descriptions/yolov5_description.md
  docs/zh_cn/algorithm_descriptions/yolov5_description.md
Labels: documentation

#228 [Fix] `concatdatasets` for voc train
  .dev_scripts/gather_models.py
  configs/yolov5/voc/yolov5_s-v61_fast_1xb64-50e_voc.py
  mmyolo/datasets/yolov5_voc.py
  tests/test_datasets/test_yolov5_voc.py
Labels: Bug:P0

#224 [Feautre] Add deploy dockerfile
  docker/Dockerfile
  docker/Dockerfile_deployment
  docs/zh_cn/advanced_guides/basic_deployment_guide.md
  docs/zh_cn/advanced_guides/yolov5_deploy.md
Labels: deployment

#237 [Feature] Add train dataset pipeline for YOLOv6 m/l
  configs/yolov6/yolov6_m_syncbn_fast_8xb32-400e_coco.py
  configs/yolov6/yolov6_s_syncbn_fast_8xb32-400e_coco.py
Labels: Feature:P0

#238 [Fix] Wrong layer number in model graph
  README.md
  README_zh-CN.md
  docs/en/algorithm_descriptions/model_design.md
  docs/en/algorithm_descriptions/yolov5_description.md
  docs/zh_cn/algorithm_descriptions/model_design.md
  docs/zh_cn/algorithm_descriptions/rtmdet_description.md
  docs/zh_cn/algorithm_descriptions/yolov5_description.md
  mmyolo/models/necks/base_yolo_neck.py
Labels: documentation

#269 [DOC] Update mmengine to `0.3.1`, mmdet to `3.0.0rc3`
  .circleci/test.yml
  README.md
  README_zh-CN.md
  docker/Dockerfile
  docker/Dockerfile_deployment
  docs/en/get_started.md
  docs/en/user_guides/yolov5_tutorial.md
  docs/zh_cn/get_started.md
  docs/zh_cn/user_guides/yolov5_tutorial.md
  mmyolo/__init__.py
  requirements/mminstall.txt
  requirements/readthedocs.txt
Labels: Bug:P0

#248 [Feature] `featmap_vis_demo` supports input image folder and url reference
  demo/featmap_vis_demo.py
  demo/image_demo.py
  mmyolo/utils/misc.py
Labels: Feature:P1

#265 [Feature] Support YOLOv6 ML model
  configs/yolov6/README.md
  configs/yolov6/metafile.yml
  configs/yolov6/yolov6_l_syncbn_fast_8xb32-300e_coco.py
  configs/yolov6/yolov6_m_syncbn_fast_8xb32-300e_coco.py
  configs/yolov6/yolov6_s_syncbn_fast_8xb32-400e_coco.py
  mmyolo/models/backbones/__init__.py
  mmyolo/models/backbones/base_backbone.py
  mmyolo/models/backbones/efficient_rep.py
  mmyolo/models/dense_heads/yolov6_head.py
  mmyolo/models/layers/__init__.py
  mmyolo/models/layers/yolo_bricks.py
  mmyolo/models/necks/__init__.py
  mmyolo/models/necks/yolov5_pafpn.py
  mmyolo/models/necks/yolov6_pafpn.py
  tests/test_models/test_backbone/test_efficient_rep.py
  tests/test_models/test_necks/test_yolov6_pafpn.py
  tools/model_converters/yolov6_to_mmyolo.py
Labels: Feature:P0

#287 [Fix] Fix mmyolo rtmdet deployment.
  mmyolo/deploy/object_detection.py
Labels: Bug:P0, deployment

#291 [Docs] Add two examples of backbone replacement and update `plugin.md` in EN
  docs/en/advanced_guides/how_to.md
  docs/en/advanced_guides/plugins.md
  docs/zh_cn/advanced_guides/how_to.md
  docs/zh_cn/advanced_guides/plugins.md
Labels: documentation

#284 [Feature] Add large image demo with `sahi`
  demo/large_image.jpg
  demo/large_image_demo.py
  docs/en/user_guides/useful_tools.md
  mmyolo/utils/large_image.py
  requirements/sahi.txt
Labels: Feature:P0

#252 [DOC] Add YOLOv6 description doc - overview
  README_zh-CN.md
  docs/zh_cn/algorithm_descriptions/index.rst
  docs/zh_cn/algorithm_descriptions/yolov6_description.md
  mmyolo/models/dense_heads/yolov6_head.py
Labels: documentation

#303 [Docs] Fix invalid urls in `user_guides/config.md`
  docs/en/user_guides/config.md
  docs/zh_cn/user_guides/config.md
Labels: documentation

#297 [Docs] Fix config.md
  docs/en/user_guides/config.md
  docs/zh_cn/user_guides/config.md
Labels: documentation

#288 [Feature] Add flag for output labelme label file in `image_demo`
  demo/image_demo.py
  mmyolo/utils/labelme_utils.py
Labels: Feature:P1

#305 [Fix] Fix scale factor type of `LetterResize` and `YOLOv5KeepRatioResize`
  mmyolo/datasets/transforms/transforms.py
  tests/test_datasets/test_transforms/test_transforms.py
Labels: Bug:P0

#294 [Refactor] Refactor some of the functionality of `dataset_analysis`
  tools/analysis_tools/dataset_analysis.py
Labels: refactoring

#308 [Feature] Add `labelme2coco` script
  tools/dataset_converters/labelme2coco.py
Labels: Feature:P0

#279 [Deploy] MMYOLO model convert to onnx for deployment.
  projects/easydeploy/README.md
  projects/easydeploy/README_zh-CN.md
  projects/easydeploy/backbone/__init__.py
  projects/easydeploy/backbone/focus.py
  projects/easydeploy/bbox_code/__init__.py
  projects/easydeploy/bbox_code/bbox_coder.py
  projects/easydeploy/docs/model_convert.md
  projects/easydeploy/model/__init__.py
  projects/easydeploy/model/backendwrapper.py
  projects/easydeploy/model/model.py
  projects/easydeploy/nms/__init__.py
  projects/easydeploy/nms/ort_nms.py
  projects/easydeploy/nms/trt_nms.py
  projects/easydeploy/tools/build_engine.py
  projects/easydeploy/tools/export.py
Labels: deployment

#289 [Docs] Deployment translation
  docs/en/deploy/basic_deployment_guide.md
  docs/en/deploy/yolov5_deployment.md
  docs/zh_cn/deploy/basic_deployment_guide.md
  docs/zh_cn/deploy/yolov5_deployment.md
Labels: deployment, documentation

#318 [Docs] Update video tutorials in `article.md`
  docs/zh_cn/article.md
Labels: documentation

#316 [Enhance] Add option of json output in `test.py`
  docs/en/advanced_guides/how_to.md
  docs/zh_cn/advanced_guides/how_to.md
  tools/test.py
Labels: application

#317 [Improvement] Add docstring and update RTMDet graph
  docs/zh_cn/algorithm_descriptions/rtmdet_description.md
  mmyolo/datasets/yolov5_coco.py
  mmyolo/deploy/object_detection.py
  mmyolo/engine/hooks/switch_to_deploy_hook.py
  mmyolo/models/backbones/csp_darknet.py
  mmyolo/models/plugins/cbam.py
  mmyolo/models/task_modules/assigners/batch_yolov7_assigner.py
Labels: Improvement

#262 [Feature] Support YOLOv5 deployment at RV1126 device
  configs/deploy/detection_rknn-fp16_static-320x320.py
  configs/deploy/detection_rknn-int8_static-320x320.py
  mmyolo/deploy/models/dense_heads/yolov5_head.py
Labels: deployment

#310 [Feature] Support YOLOv7 P6 training
  configs/yolov7/README.md
  configs/yolov7/metafile.yml
  configs/yolov7/yolov7_w-p6_syncbn_fast_8x16b-300e_coco.py
  mmyolo/models/dense_heads/yolov5_head.py
  mmyolo/models/dense_heads/yolov7_head.py
  mmyolo/models/task_modules/assigners/batch_yolov7_assigner.py
Labels: algorithm

#306 [DOC] Add custom dataset guide
  configs/yolov5/yolov5_s-v61_syncbn_8xb16-300e_coco.py
  docs/en/user_guides/custom_dataset.md
  docs/en/user_guides/index.rst
  docs/zh_cn/user_guides/custom_dataset.md
  docs/zh_cn/user_guides/index.rst
  docs/zh_cn/user_guides/yolov5_tutorial.md
  tools/dataset_converters/labelme2coco.py
  tools/misc/coco_split.py
  tools/misc/download_dataset.py
Labels: documentation, Feature:P0, application

#330 [Docs] Update EN `how_to.md` with the examples of mim
  docs/en/advanced_guides/how_to.md
  docs/zh_cn/advanced_guides/how_to.md
Labels: documentation
