Repository open-mmlab/mmyolo, pull requests merged in 2022-10, with the labels that each got.

#149 [Feature] Support YOLOv7 inference
  configs/yolov7/yolov7_l_fast_8x16b-300_coco.py
  mmyolo/models/backbones/__init__.py
  mmyolo/models/backbones/yolov7_backbone.py
  mmyolo/models/dense_heads/__init__.py
  mmyolo/models/dense_heads/yolov7_head.py
  mmyolo/models/layers/__init__.py
  mmyolo/models/layers/yolo_bricks.py
  mmyolo/models/necks/__init__.py
  mmyolo/models/necks/base_yolo_neck.py
  mmyolo/models/necks/yolov7_pafpn.py
  tools/model_converters/yolov7_to_mmyolo.py
Labels: Feature:P0

#134 [Feature] Support VOC Dataset in YOLOv5
  configs/yolov5/README.md
  configs/yolov5/metafile.yml
  configs/yolov5/voc/yolov5_l-v61_fast_1xb32-50e_voc.py
  configs/yolov5/voc/yolov5_m-v61_fast_1xb64-50e_voc.py
  configs/yolov5/voc/yolov5_n-v61_fast_1xb64-50e_voc.py
  configs/yolov5/voc/yolov5_s-v61_fast_1xb64-50e_voc.py
  configs/yolov5/voc/yolov5_x-v61_fast_1xb32-50e_voc.py
  mmyolo/datasets/__init__.py
  mmyolo/datasets/yolov5_coco.py
  mmyolo/datasets/yolov5_voc.py
  mmyolo/models/dense_heads/yolov5_head.py
  tests/data/VOCdevkit/VOC2007/Annotations/000001.xml
  tests/data/VOCdevkit/VOC2007/ImageSets/Main/test.txt
  tests/data/VOCdevkit/VOC2007/ImageSets/Main/trainval.txt
  tests/data/VOCdevkit/VOC2007/JPEGImages/000001.jpg
  tests/data/VOCdevkit/VOC2012/Annotations/000001.xml
  tests/data/VOCdevkit/VOC2012/ImageSets/Main/test.txt
  tests/data/VOCdevkit/VOC2012/ImageSets/Main/trainval.txt
  tests/data/VOCdevkit/VOC2012/JPEGImages/000001.jpg
  tests/test_datasets/test_yolov5_voc.py
Labels: planned feature

#161 [Feature] Add script converts yolo-style to coco format
  docs/en/user_guides/useful_tools.md
  docs/zh_cn/overview.md
  docs/zh_cn/user_guides/useful_tools.md
  tools/dataset_converters/yolo2coco.py
Labels: planned feature

#190 [Docs] Update config.md, faq.md and pull_request_template.md
  .github/pull_request_template.md
  docs/en/notes/faq.md
  docs/en/user_guides/config.md
  docs/zh_cn/notes/faq.md
  docs/zh_cn/user_guides/config.md
Labels: documentation

#191 [Docs] Refine config.md
  docs/en/user_guides/config.md
  docs/zh_cn/user_guides/config.md
  mmyolo/models/backbones/cspnext.py
  mmyolo/models/necks/cspnext_pafpn.py
Labels: documentation

#185 [Refector] YOLOv6 BatchTaskAlignedAssigner
  mmyolo/models/dense_heads/yolov6_head.py
  mmyolo/models/task_modules/__init__.py
  mmyolo/models/task_modules/assigners/__init__.py
  mmyolo/models/task_modules/assigners/batch_atss_assigner.py
  mmyolo/models/task_modules/assigners/batch_task_aligned_assigner.py
  mmyolo/models/task_modules/assigners/utils.py
  tests/test_models/test_detectors/test_yolo_detector.py
  tests/test_models/test_task_modules/test_assigners/test_batch_atss_assigner.py
  tests/test_models/test_task_modules/test_assigners/test_batch_task_aligned_assigner.py
Labels: Feature:P0

#196 Add visualization of the base model to the docstring.
  mmyolo/models/backbones/base_backbone.py
  mmyolo/models/necks/base_yolo_neck.py
  requirements/readthedocs.txt
Labels: documentation

#79 [Feature] support mmyolo deployment
  .circleci/test.yml
  configs/deploy/base_dynamic.py
  configs/deploy/base_static.py
  configs/deploy/detection_onnxruntime_dynamic.py
  configs/deploy/detection_onnxruntime_static.py
  configs/deploy/detection_tensorrt-fp16_dynamic-320x320-640x640.py
  configs/deploy/detection_tensorrt-fp16_static-640x640.py
  configs/deploy/detection_tensorrt-int8_dynamic-320x320-640x640.py
  configs/deploy/detection_tensorrt-int8_static-640x640.py
  configs/deploy/detection_tensorrt_dynamic-320x320-640x640.py
  configs/deploy/detection_tensorrt_static-640x640.py
  mmyolo/deploy/__init__.py
  mmyolo/deploy/models/__init__.py
  mmyolo/deploy/models/dense_heads/__init__.py
  mmyolo/deploy/models/dense_heads/yolov5_head.py
  mmyolo/deploy/object_detection.py
  tests/test_deploy/conftest.py
  tests/test_deploy/data/model.py
  tests/test_deploy/test_mmyolo_models.py
  tests/test_deploy/test_object_detection.py
Labels: deployment, Feature:P0

#200 [Docs] Fix some errors in `config.md` and `how_to.md`
  docs/en/advanced_guides/how_to.md
  docs/zh_cn/advanced_guides/how_to.md
  docs/zh_cn/user_guides/config.md
  mmyolo/models/dense_heads/yolov5_head.py
  mmyolo/models/dense_heads/yolox_head.py
Labels: documentation

#203 [Refactor] func `bbox_overlaps`
  mmyolo/models/losses/iou_loss.py
Labels: refactoring

#207 [Docs] Add examples of how to use the backbone from other repos in `how_to.md` and update `article.md`
  docs/en/advanced_guides/how_to.md
  docs/zh_cn/advanced_guides/how_to.md
  docs/zh_cn/article.md
Labels: documentation

#209 [Docs] Optimize Readthedocs page display
  docs/en/_static/css/readthedocs.css
  docs/en/conf.py
  docs/zh_cn/_static/css/readthedocs.css
Labels: documentation
