Repository open-mmlab/mmyolo, pull requests merged in 2022-12, with the labels that each got.

#304 [Improvement] `browse_dataset.py`
  tools/analysis_tools/browse_dataset.py
Labels: application, Improvement

#333 [Fix] Fix `yolov7_l_syncbn_fast_8x16b-300e_coco.py`
  configs/yolov7/yolov7_l_syncbn_fast_8x16b-300e_coco.py
Labels: Bug:P0

#342 [Fix] Fix twice head inference bug
  mmyolo/models/dense_heads/yolov5_head.py
Labels: Bug:P0

#340 [Improvement] Improve args for `browse_dataset` and supprot `RepeatDataset`
  docs/en/user_guides/useful_tools.md
  docs/zh_cn/user_guides/useful_tools.md
  tools/analysis_tools/browse_dataset.py
Labels: Bug:P0, Improvement

#338 [Fix] Fix `dataset_analysis` ProgressBar incorrect when `RepeatDataset`
  docs/en/user_guides/useful_tools.md
  docs/zh_cn/user_guides/useful_tools.md
  tools/analysis_tools/dataset_analysis.py
Labels: Bug:P0

#346 [Enhancement] Optimize the vis results of large images in `debug` mode
  demo/large_image_demo.py
Labels: enhancement

#343 [Feature] Add deploy demo
  demo/deploy_demo.py
Labels: deployment, Feature:P0, application

#360 [Improvement] Add docstring to all remaining files
  mmyolo/deploy/models/dense_heads/yolov5_head.py
  mmyolo/deploy/models/layers/bbox_nms.py
  mmyolo/deploy/object_detection.py
  mmyolo/models/task_modules/assigners/batch_yolov7_assigner.py
Labels: Improvement

#353 CodeCamp #58 [Doc] translate `rtmdet_description.md`
  docs/en/algorithm_descriptions/rtmdet_description.md
  docs/zh_cn/algorithm_descriptions/rtmdet_description.md
Labels: documentation

#365 [DOC] Add new video link for `custom dataset`
  docs/zh_cn/article.md
  docs/zh_cn/user_guides/custom_dataset.md
  tests/test_datasets/test_yolov5_voc.py
Labels: documentation

#345 [CodeCamp] Add doc of `module_combination`
  docs/zh_cn/advanced_guides/module_combination.md
Labels: documentation

#368 [Feature] Add `crowdhuman` dataset
  configs/yolov5/README.md
  configs/yolov5/crowdhuman/yolov5_s-v61_fast_8xb16-300e_crowdhuman.py
  mmyolo/datasets/__init__.py
  mmyolo/datasets/yolov5_crowdhuman.py
Labels: planned feature

#352 [CodeCamp] Add module_combination doc
  docs/zh_cn/advanced_guides/module_combination.md
  mmyolo/models/dense_heads/yolov5_head.py
Labels: documentation

#386 [Docs] Add docs about how to set the random seed
  docs/en/advanced_guides/how_to.md
  docs/zh_cn/advanced_guides/how_to.md
Labels: documentation

#378 [BUG] Fix YOLOv6 when get grid priors in `predict_by_feat` same shape will crash
  mmyolo/models/dense_heads/yolov6_head.py
Labels: Bug:P0

#392 [Feature] Add a feature for the video demo
  demo/demo.mp4
  demo/large_image_demo.py
  demo/video_demo.py
Labels: Feature:P1

#387 [BUG] Fix the scale_factor and pad_param value in LetterResize
  mmyolo/datasets/transforms/transforms.py
  tests/test_datasets/test_transforms/test_transforms.py
Labels: Bug:P1

#362 [Refactor] Refactor dataset metainfo to lowercase
  configs/yolov5/voc/yolov5_s-v61_fast_1xb64-50e_voc.py
  configs/yolov5/yolov5_s-v61_syncbn_fast_1xb4-300e_balloon.py
  demo/image_demo.py
  docs/en/index.rst
  docs/en/notes/compatibility.md
  docs/en/user_guides/yolov5_tutorial.md
  docs/zh_cn/index.rst
  docs/zh_cn/notes/compatibility.md
  docs/zh_cn/user_guides/custom_dataset.md
  docs/zh_cn/user_guides/yolov5_tutorial.md
  mmyolo/utils/boxam_utils.py
  projects/misc/custom_dataset/yolov5_s-v61_syncbn_fast_1xb32-100e_cat.py
  projects/misc/custom_dataset/yolov6_s_syncbn_fast_1xb32-100e_cat.py
  tools/analysis_tools/dataset_analysis.py
Labels: BC-breaking, refactoring

#383 [Feature] Show YOLOv5 assigner results
  projects/assigner_visualization/README.md
  projects/assigner_visualization/assigner_visualization.py
  projects/assigner_visualization/configs/yolov5_s-v61_syncbn_fast_8xb16-300e_coco_assignervisualization.py
  projects/assigner_visualization/dense_heads/__init__.py
  projects/assigner_visualization/dense_heads/yolov5_head_assigner.py
  projects/assigner_visualization/detectors/__init__.py
  projects/assigner_visualization/detectors/yolo_detector_assigner.py
  projects/assigner_visualization/visualization/__init__.py
  projects/assigner_visualization/visualization/assigner_visualizer.py
Labels: planned feature

#404 [CodeCamp] Add don't used pre-training weights to how_to
  docs/en/advanced_guides/how_to.md
  docs/zh_cn/advanced_guides/how_to.md
Labels: documentation

#381 [Doc] update the English version of `custom_dataset.md`
  docs/en/user_guides/custom_dataset.md
  docs/zh_cn/user_guides/custom_dataset.md
Labels: documentation

#377 [Feature] Support PyTorch model forward for TensorRT inference
  projects/easydeploy/model/__init__.py
  projects/easydeploy/model/backendwrapper.py
  projects/easydeploy/tools/build_engine.py
  projects/easydeploy/tools/export.py
  projects/easydeploy/tools/image-demo.py
Labels: deployment, planned feature, application

#412 [Fix] Set metainfo fields to lower case and fix CI
  .circleci/test.yml
  docs/zh_cn/user_guides/custom_dataset.md
  projects/assigner_visualization/visualization/assigner_visualizer.py
Labels: Bug:P0

#413 [Fix] Fix batch inference bug when objectness does not exist.
  mmyolo/models/dense_heads/yolov5_head.py
Labels: Bug:P0

#418 [CodeCamp] Add docs about how to freeze the weight of backbone or neck
  docs/en/advanced_guides/how_to.md
  docs/zh_cn/advanced_guides/how_to.md
Labels: documentation
