Repository open-mmlab/mmyolo, pull requests merged in 2023-03, with the labels that each got.

#603 [Feature] Support Calculate FLOPs
  README.md
  README_zh-CN.md
  docs/en/index.rst
  docs/en/recommended_topics/complexity_analysis.md
  docs/zh_cn/index.rst
  docs/zh_cn/recommended_topics/complexity_analysis.md
  mmyolo/models/dense_heads/yolov8_head.py
  tools/analysis_tools/get_flops.py
Labels: Feature:P1

#544 [Feature] Add RTMDet distillation cfg
  configs/rtmdet/README.md
  configs/rtmdet/distillation/README.md
  configs/rtmdet/distillation/kd_l_rtmdet_x_neck_300e_coco.py
  configs/rtmdet/distillation/kd_m_rtmdet_l_neck_300e_coco.py
  configs/rtmdet/distillation/kd_s_rtmdet_m_neck_300e_coco.py
  configs/rtmdet/distillation/kd_tiny_rtmdet_s_neck_300e_coco.py
  configs/rtmdet/metafile.yml
  tools/model_converters/convert_kd_ckpt_to_student.py
Labels: Feature:P0

#513 Rotated object detection and RTMDet-R
  .dev_scripts/gather_models.py
  README.md
  README_zh-CN.md
  configs/rtmdet/README.md
  configs/rtmdet/metafile.yml
  configs/rtmdet/rotated/rtmdet-r_l_syncbn_fast_2xb4-36e_dota-ms.py
  configs/rtmdet/rotated/rtmdet-r_l_syncbn_fast_2xb4-36e_dota.py
  configs/rtmdet/rotated/rtmdet-r_l_syncbn_fast_2xb4-aug-100e_dota.py
  configs/rtmdet/rotated/rtmdet-r_l_syncbn_fast_coco-pretrain_2xb4-36e_dota-ms.py
  configs/rtmdet/rotated/rtmdet-r_m_syncbn_fast_2xb4-36e_dota-ms.py
  configs/rtmdet/rotated/rtmdet-r_m_syncbn_fast_2xb4-36e_dota.py
  configs/rtmdet/rotated/rtmdet-r_s_fast_1xb8-36e_dota-ms.py
  configs/rtmdet/rotated/rtmdet-r_s_fast_1xb8-36e_dota.py
  configs/rtmdet/rotated/rtmdet-r_tiny_fast_1xb8-36e_dota-ms.py
  configs/rtmdet/rotated/rtmdet-r_tiny_fast_1xb8-36e_dota.py
  demo/large_image_demo.py
  docs/en/recommended_topics/dataset_preparation.md
  docs/en/tutorials/rotated_detection.md
  docs/zh_cn/index.rst
  docs/zh_cn/recommended_topics/dataset_preparation.md
  docs/zh_cn/tutorials/rotated_detection.md
  mmyolo/datasets/__init__.py
  mmyolo/datasets/transforms/__init__.py
  mmyolo/datasets/transforms/transforms.py
  mmyolo/datasets/yolov5_dota.py
  mmyolo/models/dense_heads/__init__.py
  mmyolo/models/dense_heads/rotated_rtmdet_head.py
  mmyolo/models/task_modules/assigners/batch_dsl_assigner.py
  mmyolo/models/task_modules/coders/__init__.py
  mmyolo/models/task_modules/coders/distance_angle_point_coder.py
  mmyolo/models/utils/misc.py
  mmyolo/utils/large_image.py
  requirements/mmrotate.txt
  requirements/tests.txt
  tests/test_models/test_dense_heads/test_rotated_rtmdet_head.py
  tests/test_models/test_task_modules/test_assigners/test_batch_dsl_assigner.py
  tests/test_models/test_utils/test_misc.py
  tools/dataset_converters/dota/README.md
  tools/dataset_converters/dota/dota_split.py
  tools/dataset_converters/dota/split_config/multi_scale.json
  tools/dataset_converters/dota/split_config/single_scale.json
  tools/model_converters/rtmdet_to_mmyolo.py
Labels: Feature:P0

#583 [Feature] Support RTMDet Ins Segmentation Inference
  configs/rtmdet/rtmdet-ins_s_syncbn_fast_8xb32-300e_coco.py
  mmyolo/datasets/utils.py
  mmyolo/models/data_preprocessors/data_preprocessor.py
  mmyolo/models/dense_heads/__init__.py
  mmyolo/models/dense_heads/rtmdet_ins_head.py
  tests/test_models/test_dense_heads/test_rtmdet_head.py
Labels: algorithm
