Repository open-mmlab/mmyolo, pull requests merged in 2023-02, with the labels that each got.

#504 [Docs] Add model structure graph of YOLOv7 in `configs\yolov7\README.md`
  configs/yolov7/README.md
Labels: documentation

#511 [Enchance] Extending `DetDataPreprocessor` flexibility
  mmyolo/datasets/utils.py
  mmyolo/models/data_preprocessors/data_preprocessor.py
  tests/test_datasets/test_utils.py
  tests/test_models/test_data_preprocessor/test_data_preprocessor.py
Labels: Feature:P0

#485 [Happy New Year] TensorRT + DeepStream Support.
  projects/easydeploy/deepstream/CMakeLists.txt
  projects/easydeploy/deepstream/coco_labels.txt
  projects/easydeploy/deepstream/configs/config_infer_rtmdet.txt
  projects/easydeploy/deepstream/custom_mmyolo_bbox_parser/nvdsparsebbox_mmyolo.cpp
  projects/easydeploy/deepstream/deepstream_app_config.txt
Labels: application

#532 [Improve] Beauty YOLOv6 head `gt_instances_preprocess`
  mmyolo/models/dense_heads/ppyoloe_head.py
  mmyolo/models/dense_heads/rtmdet_head.py
  mmyolo/models/dense_heads/yolov6_head.py
  mmyolo/models/dense_heads/yolov8_head.py
  mmyolo/models/utils/__init__.py
  mmyolo/models/utils/misc.py
  tests/test_models/test_utils/test_misc.py
Labels: Improvement

#531 [Improve] Beauty RTMDet config
  configs/rtmdet/rtmdet_l_syncbn_fast_8xb32-300e_coco.py
  configs/rtmdet/rtmdet_m_syncbn_fast_8xb32-300e_coco.py
  configs/rtmdet/rtmdet_s_syncbn_fast_8xb32-300e_coco.py
  configs/rtmdet/rtmdet_tiny_syncbn_fast_8xb32-300e_coco.py
  configs/rtmdet/rtmdet_x_syncbn_fast_8xb32-300e_coco.py
  configs/yolov5/yolov5_s-v61_syncbn_8xb16-300e_coco.py
Labels: Improvement

#537 [DOC] Fix error link
  README.md
  README_zh-CN.md
  configs/yolov5/README.md
  configs/yolov7/README.md
  configs/yolox/README.md
  docs/en/advanced_guides/plugins.md
  docs/en/get_started.md
  docs/en/user_guides/custom_dataset.md
  docs/zh_cn/advanced_guides/plugins.md
  docs/zh_cn/get_started.md
Labels: documentation

#539 [Improve] Beautify YOLOv6 all configs
  configs/yolov6/yolov6_l_syncbn_fast_8xb32-300e_coco.py
  configs/yolov6/yolov6_m_syncbn_fast_8xb32-300e_coco.py
  configs/yolov6/yolov6_n_syncbn_fast_8xb32-300e_coco.py
  configs/yolov6/yolov6_n_syncbn_fast_8xb32-400e_coco.py
  configs/yolov6/yolov6_s_syncbn_fast_8xb32-300e_coco.py
  configs/yolov6/yolov6_s_syncbn_fast_8xb32-400e_coco.py
  configs/yolov6/yolov6_t_syncbn_fast_8xb32-300e_coco.py
  configs/yolov6/yolov6_t_syncbn_fast_8xb32-400e_coco.py
Labels: Improvement

#506 [Improve] Beautify the YOLOv7 configuration
  configs/yolov7/yolov7_l_syncbn_fast_8x16b-300e_coco.py
  configs/yolov7/yolov7_tiny_syncbn_fast_8x16b-300e_coco.py
  configs/yolov7/yolov7_w-p6_syncbn_fast_8x16b-300e_coco.py
Labels: Improvement

#529 [Improve] Beautify the YOLOX configuration
  configs/yolox/yolox_l_fast_8xb8-300e_coco.py
  configs/yolox/yolox_m_fast_8xb8-300e_coco.py
  configs/yolox/yolox_nano_fast_8xb8-300e_coco.py
  configs/yolox/yolox_s_fast_8xb8-300e_coco.py
  configs/yolox/yolox_tiny_fast_8xb8-300e_coco.py
  configs/yolox/yolox_x_fast_8xb8-300e_coco.py
Labels: Improvement

#453 [Feature] Support MMRazor searchable backbone
  configs/razor/subnets/README.md
  configs/razor/subnets/rtmdet_tiny_ofa_lat31_syncbn_16xb16-300e_coco.py
  configs/razor/subnets/yolov5_s_spos_shufflenetv2_syncbn_8xb16-300e_coco.py
  configs/razor/subnets/yolov6_l_attentivenas_a6_d12_syncbn_fast_16xb16-300e_coco.py
  requirements/tests.txt
  tests/test_downstream/test_mmrazor.py
Labels: WIP, planned feature

#555 [Docs] Add twitter discord medium youtube link
  README.md
  README_zh-CN.md
Labels: documentation

#460 [Feature] Support training on a single channel image dataset.
  README.md
  README_zh-CN.md
  docs/en/common_usage/single_multi_channel_applications.md
  docs/en/index.rst
  docs/zh_cn/common_usage/single_multi_channel_applications.md
  docs/zh_cn/index.rst
Labels: documentation
