Repository open-mmlab/mmyolo, pull requests merged in 2023-01, with the labels that each got.

#426 [Docs] Update deployment doc urls in README
  README.md
  README_zh-CN.md
Labels: deployment, documentation

#425 [Feature] Implement fast version of RTMDet.
  configs/rtmdet/README.md
  configs/rtmdet/metafile.yml
  configs/rtmdet/rtmdet_l_syncbn_fast_8xb32-300e_coco.py
  configs/rtmdet/rtmdet_m_syncbn_fast_8xb32-300e_coco.py
  configs/rtmdet/rtmdet_s_syncbn_fast_8xb32-300e_coco.py
  configs/rtmdet/rtmdet_tiny_syncbn_fast_8xb32-300e_coco.py
  configs/rtmdet/rtmdet_x_syncbn_fast_8xb32-300e_coco.py
  mmyolo/models/dense_heads/rtmdet_head.py
  mmyolo/models/task_modules/assigners/__init__.py
  mmyolo/models/task_modules/assigners/batch_dsl_assigner.py
  tests/test_models/test_dense_heads/test_rtmdet_head.py
  tests/test_models/test_detectors/test_yolo_detector.py
Labels: Feature:P0

#427 [Deploy] Support YOLOv7 easy deploy
  demo/image_demo.py
  projects/easydeploy/model/model.py
  projects/easydeploy/tools/export.py
  projects/easydeploy/tools/image-demo.py
Labels: deployment, application

#434 [Fix] Fix rtmdet neck and config.
  configs/rtmdet/rtmdet_s_syncbn_fast_8xb32-300e_coco.py
  mmyolo/models/necks/cspnext_pafpn.py
Labels: Bug:P0

#433 [Fix] Fix typo in docstring
  docs/zh_cn/algorithm_descriptions/yolov6_description.md
  mmyolo/models/layers/yolo_bricks.py
Labels: documentation

#430 [Fix] Fix bugs in the output annotation file when `--class-id-txt` is set.
  tools/dataset_converters/labelme2coco.py
Labels: Bug:P0

#384 [DOC] Update useful_tools.md
  docs/zh_cn/user_guides/useful_tools.md
Labels: documentation

#382 [CodeCamp]Add doc of yolov6_description.md
  docs/zh_cn/algorithm_descriptions/yolov6_description.md
Labels: documentation, CLA not signed

#259 [Feature] Support PPYOLOE training
  configs/ppyoloe/README.md
  configs/ppyoloe/metafile.yml
  configs/ppyoloe/ppyoloe_l_fast_8xb20-300e_coco.py
  configs/ppyoloe/ppyoloe_m_fast_8xb28-300e_coco.py
  configs/ppyoloe/ppyoloe_plus_l_fast_8xb8-80e_coco.py
  configs/ppyoloe/ppyoloe_plus_m_fast_8xb8-80e_coco.py
  configs/ppyoloe/ppyoloe_plus_s_fast_8xb8-80e_coco.py
  configs/ppyoloe/ppyoloe_plus_x_fast_8xb8-80e_coco.py
  configs/ppyoloe/ppyoloe_s_fast_8xb32-300e_coco.py
  configs/ppyoloe/ppyoloe_s_fast_8xb32-400e_coco.py
  configs/ppyoloe/ppyoloe_x_fast_8xb16-300e_coco.py
  mmyolo/datasets/transforms/__init__.py
  mmyolo/datasets/transforms/transforms.py
  mmyolo/datasets/utils.py
  mmyolo/engine/hooks/__init__.py
  mmyolo/engine/hooks/ppyoloe_param_scheduler_hook.py
  mmyolo/models/data_preprocessors/__init__.py
  mmyolo/models/data_preprocessors/data_preprocessor.py
  mmyolo/models/dense_heads/ppyoloe_head.py
  mmyolo/models/dense_heads/yolov6_head.py
  mmyolo/models/task_modules/assigners/batch_atss_assigner.py
  mmyolo/models/task_modules/coders/distance_point_bbox_coder.py
  model-index.yml
  tests/test_datasets/test_transforms/test_transforms.py
  tests/test_datasets/test_utils.py
  tests/test_models/test_data_preprocessor/test_data_preprocessor.py
  tests/test_models/test_dense_heads/test_ppyoloe_head.py
  tools/model_converters/ppyoloe_to_mmyolo.py
Labels: Feature:P0, algorithm

#349 [CodeCamp] #50 Add module combination doc
  docs/zh_cn/advanced_guides/module_combination.md
Labels: documentation

#442 [Docs] Update model graphs
  configs/rtmdet/README.md
  configs/yolov5/README.md
  configs/yolov6/README.md
  configs/yolox/README.md
  docs/en/algorithm_descriptions/yolov5_description.md
  docs/zh_cn/algorithm_descriptions/yolov5_description.md
Labels: documentation

#401 [Docs] Add an example project to 'projects\' folder
  projects/example_project/README.md
  projects/example_project/configs/yolov5_s_dummy-backbone_v61_syncbn_8xb16-300e_coco.py
  projects/example_project/dummy/__init__.py
  projects/example_project/dummy/dummy_yolov5cspdarknet.py
Labels: documentation

#452 [Fix] Fix import error in `optimize_anchors.py`
  tools/analysis_tools/optimize_anchors.py
Labels: Bug:P0

#450 [Feature] Add new YOLOX bbox coder for TensorRT-8 and fix TensorRT-7 bug
  projects/easydeploy/bbox_code/__init__.py
  projects/easydeploy/bbox_code/bbox_coder.py
  projects/easydeploy/model/model.py
  projects/easydeploy/nms/trt_nms.py
Labels: deployment

#456 [Deploy] Support YOLOv8 deploy
  projects/easydeploy/backbone/__init__.py
  projects/easydeploy/backbone/common.py
  projects/easydeploy/model/model.py
  projects/easydeploy/tools/export.py
  projects/easydeploy/tools/image-demo.py
Labels: deployment

#469 [Fix] Fix requirement about only ONNXRuntime without TensorRT
  projects/easydeploy/model/backendwrapper.py
Labels: Bug:P1

#461 [DOC] Add YOLOv8 docs
  README_zh-CN.md
  docs/en/algorithm_descriptions/index.rst
  docs/en/algorithm_descriptions/yolov8_description.md
  docs/zh_cn/algorithm_descriptions/index.rst
  docs/zh_cn/algorithm_descriptions/yolov8_description.md
  docs/zh_cn/article.md
Labels: documentation

#458 [Feature] Support YOLOv8 training
  README.md
  README_zh-CN.md
  configs/yolov8/README.md
  configs/yolov8/metafile.yml
  configs/yolov8/yolov8_l_syncbn_fast_8xb16-500e_coco.py
  configs/yolov8/yolov8_m_syncbn_fast_8xb16-500e_coco.py
  configs/yolov8/yolov8_s_syncbn_fast_8xb16-500e_coco.py
  mmyolo/models/backbones/csp_darknet.py
  mmyolo/models/dense_heads/yolov8_head.py
  mmyolo/models/losses/iou_loss.py
  mmyolo/models/task_modules/assigners/batch_task_aligned_assigner.py
  model-index.yml
  requirements/mminstall.txt
  requirements/readthedocs.txt
  tests/test_models/test_backbone/test_csp_darknet.py
  tests/test_models/test_dense_heads/test_yolov8_head.py
  tests/test_models/test_detectors/test_yolo_detector.py
Labels: Feature:P0, algorithm

#471 [Doc] Add PPYOLOE model structure
  configs/ppyoloe/README.md
Labels: documentation

#481 [Docs] Update `article.md` and `model_zoo.md`
  docs/en/model_zoo.md
  docs/zh_cn/article.md
  docs/zh_cn/model_zoo.md
Labels: documentation

#482 [Docs] Refine README
  README.md
  README_zh-CN.md
Labels: documentation
